### ISSUE TITLE
Safari users on iOS can't select XBull. 

### ISSUE THREAD

**Issue by MatejMecka** [bigger-tech/simple-stellar-signer#163]
Scenario: an iOS user has Safari as their browser and wants to connect their wallet.

Expected Behavior: User gets to the wallet selection page -> They select the wallet -> XBull opens
What happens: User gets to the wallet selection page -> They select the wallet -> XBull gets blocked from loading

This might be happening on other wallets I have not tested it yet.

**Comment by fsodano** [comment]
Thank you for reporting! We'll get on to it straight away!

**Comment by fsodano** [comment]
@MatejMecka we've been trialing but we think it might be an issue with xBull itself, we've pinged earrietadev to see if he can confirm. Thanks again for reporting :)

**Comment by earrietadev** [comment]
@fsodano The issue is with how simple signer is doing the connection, I forked the repo in order to open a pull request but I can't commit because of a pre-commit configuration and I can't do the fix myself but this is what it needs to be done in simple signer code:

file `src/lib/wallets/xBull/XBull.ts` at methods `getPublicKey` and `sign`:

```
    public override async getPublicKey(): Promise<string> {
        const bridge = new xBullWalletConnect();
        const publicKey = await bridge.connect();
        bridge.closeConnections();
        super.persistWallet();
        return publicKey;
    }
```
```
    public override async sign(tx: Transaction): Promise<string> {
        const bridge = new xBullWalletConnect();
        const signedXdr = await bridge.sign({ xdr: tx.toXDR() });
        bridge.closeConnections();
        return signedXdr;
    }
```

Once those two methods are updated the connection with xBull works without issues

**Comment by fsodano** [comment]
Perfect, thank you so much @earrietadev ! @Ja-boop please have a look.

**Comment by MatejMecka** [comment]
Thanks for fixing this issue so quickly! <3

**Comment by Ja-boop** [comment]
@MatejMecka Thank you so much for letting us know about this issue!
