### ISSUE TITLE
Investigate which frontend framework to use

### ISSUE THREAD

**Issue by fsodano** [bigger-tech/simple-stellar-signer#5]
Hyperapp and Svelte have comparable bundle sizes. @RivarolaNicolas please attach your findings as a comment.

The team feels more confident with Svelte as it has a better developer experience. This ticket is about all team members creating two sample apps with Svelte to get familiar with it.

**Comment by RivarolaNicolas** [comment]
The reason we were going to use Hyperapp was because of its final bundle size, as keeping the project as lightweight as possible is one of our main goals.

After researching we found that Hyperapp and Svelte have comparable bundle sizes, as shown in these links:

https://bundlephobia.com/package/svelte@3.46.2

https://bundlephobia.com/package/hyperapp@2.0.20

After taking that into account we decided to give Svelte a try, and we found it more dev-friendly than Hyperapp. Taking in consideration the huge community that Svelte has (compared to Hyperapp), meaning a more robust ecosystem (Svelte Dev Tools, different router libraries, etc) we decided to use Svelte.
